### ISSUE TITLE
Libraries (Build) menu behavior

### ISSUE THREAD

**Issue by freddie-freeloader** [scalacenter/scastie#131]
The **Libraries (Build)** menu creates a lot of inconsistencies UX-wise as soon as it is open:

- If one clicks on **Help** nothing happens (it is just displayed as soon as one switches back to **Edit**)
- One can still use the buttons **Clear**, **Format** and **Console** therefore interact more or less obvious with the editor

I would propose to move the Libraries button to the top and hide all buttons on the left, when the **Libraries (Build)** menu is shown.

**Comment by MasseGuillaume** [comment]
This is a really good idea. Do you want to try implement it :D ?

**Comment by MasseGuillaume** [comment]
Where to look: [SideBar.scala](https://github.com/scalacenter/scastie/blob/master/client/src/main/scala/com.olegych.scastie.client/SideBar.scala)

**Comment by arminio** [comment]
I'll have a go to see if I can implement this feature

**Comment by arminio** [comment]
Where exactly would you like the Libraries button to be moved to? Do you still want it to be on the sidebar, but at its top? Or would you like it to be moved to the top bar? 
The confusion is caused by the part of the original comment where it says:

> ... and hide all buttons on the left, when the Libraries (Build) menu is shown.

If the Libraries button is moved to the top of the sidebar and other buttons on the sidebar are hidden, then we will have no way of getting out that page.

**Comment by arminio** [comment]
Also, was just wondering if making the help a modal dialog might be a better solution ?

**Comment by MasseGuillaume** [comment]
> Also, was just wondering if making the help a modal dialog might be a better solution ?

Yeah that would be better. Right now it's hacked in via annotations

> If the Libraries button is moved to the top of the sidebar and other buttons on the sidebar are hidden, then we will have no way of getting out that page.

I think the idea is to display on the sidebar:

In Edit View:
* **Run**
* Library
* Clear
* Format
* Console
* ... Sharing

In Library View:
* a Button to go back to the Editor View
* **Library**

**Comment by arminio** [comment]
> In Library View:
> 
> a Button to go back to the Editor View

Isn't that feature already is available via clicking on the 'Edit' on the sidebar to go back to the Editor?

![image](https://cloud.githubusercontent.com/assets/498781/23499580/95bb9008-ff24-11e6-9a37-a3c7203bfce8.png)

**Comment by MasseGuillaume** [comment]
@arminio In the library View you should not see Format, Console, etc since they don't do anything for this particular view.

**Comment by arminio** [comment]
A few quick questions.
When the Libraries is selected:
1. Should all other buttons on the sidebar be hidden?
2. Should the Libraries **view** have a close button, clicking which closes the Libraries view and moves the focus to the Run?

If the answers to both these 2 questions are yes, then the libraries view sounds like it needs to be a modal dialog.

**Comment by MasseGuillaume** [comment]
There is 3 Views

* Editor
* Snippets (UserProfile)
* Libraries (Build)

There is multiple actions
* Run
* Clear
* Format
* Open Console
* Save / Update / Amend / Fork

All the actions above only make sense in the context of the Editor.

I think a good way to solve this problem is with Ribbons:
![ms words ribons](http://www.word-tips.com/wp-content/uploads/microsoft-office-ribbon-1.gif)

Here the `Home` Views has different actions: Change Font, Clipboard, etc.

**Comment by heathermiller** [comment]
Just to clarify, I think the suggestion made by @MasseGuillaume is – perhaps we don't need a modal for the libraries/build page, and instead we can just change what's displayed on the left bar when we're in the libraries/build pane. So, display only a subset of buttons on the left when in the libraries/build pane.

**Comment by arminio** [comment]
I understand now. Thank you for the explanations.

**Comment by arminio** [comment]
Please review the implemented change and feel free to change the Library svg's that I have added/used if you like.
