### ISSUE TITLE
make help menu in a modal

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#132]
users find it confusing that it's an instrumentation.

For example:

```scala
1 + 1 // [cursor]
> HELP
> MENU
> BLOCK
```

when you press enter the cursor will jump the big help block and you might loose track of your cursor.

**Comment by vladap** [comment]
For a record - my original confusion:
"The first thing I wanted to try was to click a type some code and compile. If you click next to code "List("Hello", "World").mkString("", ", ", "!")" and press Enter, expecting to get next line, it actually jumps to the code bar at the bottom. Which is unexpected because I didn't know it is even there. There is the first code line, then long help, then bar where I can put additional code. On a smaller screen the bottom bar can be even off-screen, which means it would be even harder to fined where my cursor jumped.

It is ok without help, but for the first time there is help opened.

I think it is better to have a bit of help off-screen because first time user will infer to scroll. As well the console where to put Scala code is the central part"

**Comment by MasseGuillaume** [comment]
@vladap updated the example

**Comment by heathermiller** [comment]
@MasseGuillaume, the help dialog as a modal is part of 47 Degrees UI design, right?
