### ISSUE TITLE
take advantage of scala-js-react Reusability

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#209]
more details here: https://github.com/scalacenter/scastie/pull/202

**Comment by japgolly** [comment]
Hi! Just another suggestion: The VDOM for Scastie isn't overly complex. Say 80ms is your acceptable performance window for a render cycle, without measuring I'd guess that you're not in danger of exceeding that. Therefore I wouldn't recommend adding Reusability to too many components because it can add complexity and/or affect code-readability in some cases, depending on the component. I'd probably just do it for a few of the top-level, big, composite components like the top bar, the side bar, the bottom bar. 

If you're interested in measuring, it's quite easy and kind of fun ([see](https://facebook.github.io/react/docs/perf.html)).
You can even start the profiler, play around in the app, stop the profiler then ask it about ["wasted" time](https://facebook.github.io/react/docs/perf.html#printwasted) which will tell you where you'd get the most benefit from Reusability.

**Comment by japgolly** [comment]
Oh and btw [`Reusability.shouldComponentUpdateWithOverlay`](https://japgolly.github.io/scalajs-react/#examples/reusability) (as opposed to just `Reusability.shouldComponentUpdate`) might be of use during development.

**Comment by MasseGuillaume** [comment]
Every component now have Reusability.shouldComponentUpdate
