### ISSUE TITLE
I can't see all of my saved snippets

### ISSUE THREAD

**Issue by heathermiller** [scalacenter/scastie#219]
I see maybe 10-12 in my list of snippets, but once a snippet pops off the bottom of the list, I can't ever find it again. There's no pagination on the snippets list and it seems to only show a limited number of snippets.

**Comment by MasseGuillaume** [comment]
I cannot reproduce. Can you provide more details? Maybe a screenshot.

**Comment by heathermiller** [comment]
I can show a screenshot, sure, but I'm not sure it would help.

Here's a little video (sorry, my gif got messed up):
https://youtu.be/DfIuHt554PA

The problem is that I have created more snippets than are shown in my list of saved snippets. I don't know where they went. It's happening with new snippets that I'm saving – they're just not in the list I can see. I'm guessing it's because they're listed somehow randomly. Things I've previously saved are also gone. 

If the snippets are being saved somewhere that just isn't shown to me in my UI, great. Let's fix the UI and add pagination or something. If my snippets are being lost/deleted, that's another story...

@MasseGuillaume can you see every snippet you've ever created in your list of snippets?

**Comment by MasseGuillaume** [comment]
This is strange. There is no pagination, I always show all your snippets. If you have 1000 snippets they all should be on a giant list.

The only thing that I see could go wrong is serialization/deserialization. I'm using upickle to handle that, it means when I add a new field to the input model, I also need to set a default value. Otherwise, when I try to deserialize an older model it fail. With the deprecation of upickle (see https://github.com/scalacenter/scastie/issues/189) I need to find a new alternative. What I like about upickle is that I can use it across the codebase (read a snippet from file, read inputs from local storage, use it as a protocol for akka-remote).

**Comment by MasseGuillaume** [comment]
Can you try again, it should be restored now.

**Comment by MasseGuillaume** [comment]
I ran a migration script and made sure there is no failure reading old data. Everything should be in order now.
