### ISSUE TITLE
Offset the autocompletion in worksheet mode

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#225]

**Comment by olafurpg** [comment]
This should be doable with the scalafix token patch api. The implementation for applying token patches is here https://github.com/scalacenter/scalafix/blob/d10d3cac39369a5894e8fe2fa605f671e445b066/scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala#L155-L164 In particular, in line 162 we can keep track the offset of the current token and the offset in the new source file being being constructed. I may even add this support in scalafix myself since it will be useful for metadoc.

Porting the Scastie `Patch` to `scalafix.Patch` should be quite simple. I'm happy to give more pointers if someone wants to work on this.

**Comment by dimart** [comment]
Hi @olafurpg, thanks for your suggestion! 
Although I think I found a simpler solution – you can check it here #268.

**Comment by olafurpg** [comment]
@dimart awesome! If you can pass the uninstrumented version to ensime then that much better 😄

**Comment by dimart** [comment]
@olafurpg thanks! Fortunately, we can 😄
