### ISSUE TITLE
keep cursor position on reformatting

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#27]

**Comment by olafurpg** [comment]
This might be doable by extending scalafmt. Would be a cool addition to the
library api

**Comment by heathermiller** [comment]
Do you think you could do it, @olafurpg?

**Comment by heathermiller** [comment]
Else I don't think that the formatting button is really a "must have" for scastie... We could just put it off and focus on more important issues.

**Comment by olafurpg** [comment]
It's totally doable but I don't think this is a critical issue. The
formatting button is already implemented and it's actually quite nice to
have if you paste indented code from a file into a scastie worksheet.

**Comment by MasseGuillaume** [comment]
@olafurpg this is a ui bug.

@heathermiller its really usefull

**Comment by heathermiller** [comment]
It's not bad to have, but to be honest, of all of the things we need to focus on, I think spending time focusing on adding one of our personal projects to Scastie was really quite unnecessary.

**Comment by olafurpg** [comment]
I admit the hour we spent on adding the formatting button was fun : ) We had just spent several hour tracking down a concurrency issue in the sbt runner, so adding the formatting button was an easy task to do at the end of the day.

I agree this issue is not urgent I think it totally fine to document the bug however. It might be an excellent issue for a first-time contributor.

**Comment by heathermiller** [comment]
Ok, understood. Though let's please try to stay on task. Happy that everyone agrees that this is not essential to focus on. And yes, indeed this is a good first-time contributor fix!
