### ISSUE TITLE
Unclear what "Script" does

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scastie#57]
Hovering over the icon does not reveal alt text

**Comment by MasseGuillaume** [comment]
When using the Script Mode:
When a user evaluate a `main` method or a `App trait`
I display an info message
I turn off script mode for this evaluation 
example: https://scastie.scala-lang.org/834

When not using the Script Mode (Let's call this Program Mode)
When a user has non top-level statements in top-level position. For example `val a = 1` without wrapping it with a class
I display an info message  (https://scastie.scala-lang.org/836)
I do not turn the Script Mode on since the Program Mode is helpful to report compiler error

I think an alt text is no enough space to explain what the Script Mode does. I guide the user if he does not use the mode properly.

@heathermiller @olafurpg does that solves the issue?

**Comment by heathermiller** [comment]
This is good @MasseGuillaume! I would update the wording of the error messages, but the logic for when they're invoked is perfect.

**Comment by heathermiller** [comment]
For example, you write:

> You dont need an entry point (`def main(args: Array[String]): Unit` or `extends App`) in Script Mode

I'd just say:

> You don't need a `main` method (or `extends App`) in Script mode.

I think this wording is clearer.

**Comment by heathermiller** [comment]
Also, what about renaming "script mode" to "worksheet mode" since people already use the word "worksheet" for this kind of functionality?

**Comment by heathermiller** [comment]
For the other case, you write:

> expected class or object definition
> Use The Script Mode

I'd say instead,

> expected class or object definition
> It seems you're writing code without an enclosing class/object, and without a `main` method. Switch to script mode if you want to use scastie more like a REPL.
