### ISSUE TITLE
Prettification of symbols is over eager

### ISSUE THREAD

**Issue by jackkoenig** [scalacenter/scastie#841]
### Describe the bug

<= and >= are turned into unicode even when they are included in a larger symbol

### Scastie snippet link

https://scastie.scala-lang.org/L3raNM8IRNWHoyblusCQZw

### To Reproduce

Type operators like `:<=`, `:>=` or `:<>=`, they all get ruined a bit by the attempted prettification of `<=` and `>=`.

### Expected behavior

It would be nicer for users of Chisel (which uses the mentioned symbols as operators) if the operators were left alone, basically if the prettification of `<=` and `>=` did not occur if when they are included in a larger symbol.

### Screenshot ( Optional )

![Screen Shot 2023-05-10 at 5 12 02 PM](https://github.com/scalacenter/scastie/assets/8584418/da52c71f-610d-4ab5-8d1e-94e1bc0b429c)

### Version

Scastie website

### What browsers are you seeing the problem on?

Chrome

**Comment by sarthaknimbalkar** [comment]
Hello @jackkoenig, @rochala 

After giving it a thought, I came up with this:
One possible approach is to use alternative representations or combinations of characters that achieve the desired functionality. For example, instead of using :<= or :>=, you can try using :<<= and :>>= respectively, which use the shift-left and shift-right operators << and >> along with the assignment operator =. This way, the symbols <= and >= are not part of the larger symbol and are less likely to be affected by the prettification. 

Would this possibly work ?

**Comment by rochala** [comment]
I think that generally there should be no prettification at all, or preferably it should be possible to toggle in some editor configuration panel which is not here ;(. For now I'll fix it by removing ligatures completely from Scastie.

**Comment by jackkoenig** [comment]
I tend to think that prettification is one of these "too cute by half" sorts of features. Having it be togglable would definitely be the best for all use cases though!

**Comment by jackkoenig** [comment]
Thanks for fixing this @rochala! Any idea on when the fix will be deployed?

**Comment by rochala** [comment]
It will be deployed today / tomorrow along with latest Scala support.

**Comment by rochala** [comment]
@jackkoenig the changes are now deployed :D
